"""
Migration scripts directory for Alembic.

This directory contains all database migration scripts generated by Alembic.
Each migration file represents a version change to the database schema.

Google Python Style Guide conventions are followed throughout.
"""
