"""Initial migration: create series and measurements tables

Revision ID: f1b0fb5ef51e
Revises: 
Create Date: 2026-02-21 13:59:57.459161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1b0fb5ef51e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration upgrade.

    This function contains the steps necessary to upgrade the database
    schema to the current revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('state_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_name', 'categories_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_categories_catalog_id'), 'categories_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_categories_catalog_name'), 'categories_catalog', ['name'], unique=False)
    op.create_table('series_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregation_method', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_series_name', 'series_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_series_catalog_id'), 'series_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_series_catalog_name'), 'series_catalog', ['name'], unique=False)
    op.create_table('categorical_measurements',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['categories_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timestamp', 'series_id')
    )
    op.create_index('idx_categorical_series_id', 'categorical_measurements', ['series_id'], unique=False)
    op.create_index('idx_categorical_time', 'categorical_measurements', ['timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_categorical_measurements_series_id'), 'categorical_measurements', ['series_id'], unique=False)
    op.create_index(op.f('ix_categorical_measurements_timestamp'), 'categorical_measurements', ['timestamp'], unique=False)
    op.create_table('measurements',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timestamp', 'series_id')
    )
    op.create_index('idx_measurements_series_id', 'measurements', ['series_id'], unique=False)
    op.create_index('idx_measurements_time', 'measurements', ['timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_measurements_series_id'), 'measurements', ['series_id'], unique=False)
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply migration downgrade.

    This function contains the steps necessary to downgrade the database
    schema to the previous revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_series_id'), table_name='measurements')
    op.drop_index('idx_measurements_time', table_name='measurements', postgresql_using='btree')
    op.drop_index('idx_measurements_series_id', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_categorical_measurements_timestamp'), table_name='categorical_measurements')
    op.drop_index(op.f('ix_categorical_measurements_series_id'), table_name='categorical_measurements')
    op.drop_index('idx_categorical_time', table_name='categorical_measurements', postgresql_using='btree')
    op.drop_index('idx_categorical_series_id', table_name='categorical_measurements')
    op.drop_table('categorical_measurements')
    op.drop_index(op.f('ix_series_catalog_name'), table_name='series_catalog')
    op.drop_index(op.f('ix_series_catalog_id'), table_name='series_catalog')
    op.drop_index('idx_series_name', table_name='series_catalog')
    op.drop_table('series_catalog')
    op.drop_index(op.f('ix_categories_catalog_name'), table_name='categories_catalog')
    op.drop_index(op.f('ix_categories_catalog_id'), table_name='categories_catalog')
    op.drop_index('idx_categories_name', table_name='categories_catalog')
    op.drop_table('categories_catalog')
    # ### end Alembic commands ###
